# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c625569d16d43db0b495295de092be68ff88b713cfd6cf4a500e2355cc07abc159d146766526c02f4dfdeb8e7e3c9b29474c2c0f0f5ff1806d9d3e76d53cad3

test:
  secret_key_base: 88f5e35e97646ecf2c39496ff2cc7c4232ce9495cc19007aa816ba1ae8ec6e616076941b0e066156ea0bd5f952d28cceba2f8e8ddeaf22eac4432f7a8424dadd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
